name: Checkout
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before
        run: ls -lha
      - uses: actions/checkout@v3
      - name: List File After
        run: ls -lha