name: DynamicMatrix
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System to run on'
        type: string
        default: "windows-latest,ubuntu-latest"
      node-version:
        description: 'Node.js version to use'
        type: string
        default: "14,15,16"
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-arrays: ${{ steps.matrix-arrays.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: "return {os: context.payload.inputs['os'].split(','),
                  'nodeVersion': context.payload.inputs['node-version'].split(',') }"
          result-encoding: json
        id: matrix-arrays
      - run: echo ${{ steps.matrix-arrays.outputs.result}}
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value2" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo '${{ steps.step-1.outputs.step-output}}'
          echo '${{ steps.step-2.outputs.step-output}}'
  node-matrix:
    needs: prepare-matrix
    strategy:
      matrix:
        os: ${{needs.prepare-matrix.outputs.matrix-arrays.os}}
        node-version: ${{ needs.prepare-matrix.outputs.matrix-arrays}}
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v