name: Repository Events
on: 
  push:
    branches: [main, "feature/*", "bugfix/*", "hotfix/*", "release/*", "!develop"]
    tags: ["v*"]
    paths: ["**.js"]
  pull_request:
    types: [opened, reopened, synchronize, assigned]
    branches: [main]
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3