name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Contexts
        id: contexts
        run: |
          echo -e 'GitHub Context: ${{ toJson(github) }}\n\n'
          echo -e 'Job Context: ${{ toJson(job) }}\n\n'
          echo -e 'Secrets Context: ${{ toJson(secrets) }}\n\n'
          echo -e 'Steps Context: ${{ toJson(steps) }}\n\n'
          echo -e 'Runner Context: ${{ toJson(runner) }}\n\n'