name: External Events
on:
  repository_dispatch:
    types: [build]

jobs:
  echo-a-string:
    runs-on: ubuntu:latest
    steps:
      - name: Echo a String 
        run: echo "Repository Dispatch Event Triggered"