name: Manually Triggered

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        type: string
        required: true
      greeting:
        type: choice
        options: 
        - Hello
        - Bye
        default: Hello
        description: 'String to use in the greeting'
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print REF
        run: echo "$GITHUB_REF"
      - name: Print Input
        run: |
          echo "String: ${{ inputs.string }}"
      - name: Send greeting
        run: echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.message }}"