name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 65
        timeout-minutes: 1
      - name: Step 2
        continue-on-error: true
        id: step-2
        run: exit 1
      - name: Runs on Step 2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo "This step runs only if the step 2 fails."
      - name: Runs on Failure
        if: failure()
        run: echo "Failure"
      - name: Runs on Success
        if: success() # default behavior
        run: echo "This step runs only if the previous step succeeds."
      - name: Runs on Always
        if: always()
        run: echo "This step runs regardless of the previous step's outcome."
      - name: Runs on Cancelled
        if: cancelled()
        run: echo "This step runs only if the workflow is cancelled."
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo "This job runs only if job-1 fails."